---
title: "sensitivity_scores_db"
author: "Thea Rolskov Sloth"
date: "11/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading packages and data}
library(pacman)
p_load(plotly, jpeg, tm, brms, tidyverse, tidybayes, ggplot2, LaplacesDemon, rethinking, tidyr, reshape2, tibble, stringr, here, data.table, mousetrap)

#setting working directory
setwd("~/Bachelor-MM-/decision_bias")

#data
data_db <- read.csv("data_db.csv")[,2:41]
disagree_db <- read.csv("disagree_db.csv")[,2:41]

```

```{r remove joint columns in data_db }
data_db <-  data_db %>% select(-contains('oint'))

data_db <- data_db[,1:30]

```


#Transforming to long format

```{r making long format, include = FALSE}

#create dataframe with only data from left player
left <- data_db %>% select(-contains('right'))

#create dataframe with only data from right player
right <- data_db %>% select(-contains('left'))


#rename columns to not contain left or right
names(left) <- gsub(pattern = "_left", replacement = "", x = names(left))
names(right) <- gsub(pattern = "_right", replacement = "", x = names(right))


#make same type of column in subject (factor)
right$SubjectID <- as.factor(right$SubjectID)
left$SubjectID <- as.factor(left$SubjectID)

#make column that specifies side
right$Side <- as.factor("right")
left$Side <- as.factor("left")


#Joining the dataframes
long_data_db <- rbind(left, right)

```

## Create models for sensitivity scores

```{r get priors, define priors and prior predictive check, eval = FALSE}

#use get prior function
get_prior(response_dummy ~ diff + (1 + diff|SubjectID_unique), family = "bernoulli", data = long_data_db)

#Defining priors
prior_sensitivity =  c(
  prior(normal(0,0.1), class = "b", coef = "diff"),
  prior(normal(0,0.2), class = "Intercept"),
  prior(normal(0,0.1), class = "sd", coef = "diff", group = "SubjectID_unique"),
  prior(normal(0,0.2), class = "sd", coef = "Intercept", group = "SubjectID_unique")
)


#Prior predictive check
prior_check_sensitivity <- brm(response_dummy ~ diff + (diff|SubjectID_unique), 
                               prior = prior_sensitivity,
                               data = long_data_db, 
                               sample_prior = "only",
                               iter = 4000, 
                               family = "bernoulli",
                               cores=2,
                               chains=2)

pp_check(prior_check_sensitivity,nsamples = 100)

```


```{r sensitivity model, eval = FALSE}
#Making the model - using answer
m_sensitivity <- brm(
  response_dummy ~ diff + (1+diff|SubjectID_unique),
  data = long_data_db,
  prior = prior_sensitivity,
  family = "bernoulli", #As we had a binary outcome, we set this to "bernoulli"
  seed = 123,# Adding a seed makes results reproducible.
  cores=4,
  chains=4,
  control = list(adapt_delta = 0.9)
) 

m_sensitivity

```


#Saving model estimated for sensitivity
```{r save the sensitivity estimates}
#Saving random effect for individual intercept
random_effects_intercept <- as.data.frame(ranef(m_sensitivity))[,1:2] 

#Saving random effect for individual slope
random_effects_slope <- as.data.frame(ranef(m_sensitivity))[,5:6]

#Saving fixed effects 
fixed_effects <- as.data.frame(fixef(m_sensitivity)) #Making data frame of fixed effects

#Make an empty dataframe
sensitivity_scores = data.frame(matrix(vector(), 128, 2,
                dimnames=list(c(), c("Intercept", "Slope"))),
                stringsAsFactors=F)

#Add fixed effects of intercept to random effects of intercept
sensitivity_scores$Intercept <- random_effects_intercept[,1] + fixed_effects[1,1]

#Add fixed effects of slope to random effects of slope
sensitivity_scores$Slope <- random_effects_slope[,1] + fixed_effects[2,1] #last year done differently

#Adding rownames
sensitivity_scores <- cbind(Row.Names = rownames(random_effects_intercept), as.data.frame(sensitivity_scores))

#Duplicating comlumn, but as a character so we can use it to merge later
sensitivity_scores$SubjectID_unique <- as.character(sensitivity_scores$Row.Names)

#Removing first column
sensitivity_scores <- sensitivity_scores[,2:4]

```


```{r merge sensitivity scores with long_data_db}
long_data_db <- merge(long_data_db,sensitivity_scores, by="SubjectID_unique")
```


#Plotting the model 

```{r slopes for individuals in single plots, eval = FALSE}
marginal_effects(
  m_sensitivity,
  "diff", 
  conditions = distinct(long_data_db, SubjectID_unique),
  re_formula = NULL
  )
```

```{r marginal effects, classic, eval = FALSEW }
marginal_effects(m_sensitivity)
```

```{r plots that did not work, eval = FALSE, include = FALSE}


spaghetti(m_sensitivity, xvar = "diff", spage)

marginal_effects(m_sensitivity, spaghetti = TRUE, nsamples = 100)

out_f <- marginal_effects(
  m_sensitivity,
  "diff"
  )[[1]]

out_r <- marginal_effects(
  m_sensitivity,
  "diff", 
  conditions = distinct(long_data_db, SubjectID_unique),
  re_formula = NULL
  )[[1]]


out_r %>% 
  ggplot(aes(diff, response_dummy)) +
  geom_ribbon(
    data = out_f,
    aes(ymin = lower__, ymax = upper__),
    alpha = .33
  ) +
  geom_line(data = out_f, size = 0.01) +
  geom_line(aes(group = SubjectID_unique))


forest(m_sensitivity)

ranef(m_sensitivity)

marginal_effects(ranef(m_sensitivity))

sjp.lmer(m_sensitivity, vars = "c12hour", type = "ri.slope")


 
```


#Making wide format with results from the sensitivity model
```{r create dataframe that only contains the columns which we would like to merge into wide format}

#Make dataframe with intercept, slope, side, and unique subject
sensitivity_scores <- distinct(long_data_db, SubjectID_unique, Side, Intercept, Slope)

```


```{r make wide to merge with disagree data}
#Duplicating SubjectID to make into a character
sensitivity_scores$temp_SubjectID_unique <- as.character(sensitivity_scores$SubjectID_unique)

#deselect the old column
sensitivity_scores <- subset(sensitivity_scores, select = -c(SubjectID_unique))

#rename to the old name
names(sensitivity_scores)[names(sensitivity_scores) == "temp_SubjectID_unique"] <- "SubjectID_unique"


#Dividing into left and right data
sensitivity_scores_right <- filter(sensitivity_scores, Side == "right")
sensitivity_scores_left <- filter(sensitivity_scores, Side == "left")

#Deleting side column
sensitivity_scores_right <- subset(sensitivity_scores_right, select = -c(Side))
sensitivity_scores_left <- subset(sensitivity_scores_left, select = -c(Side))

#Renaming columns
colnames(sensitivity_scores_left) <-  c("Intercept_left", "Slope_left", "SubjectID_left_unique")
colnames(sensitivity_scores_right) <-  c("Intercept_right", "Slope_right", "SubjectID_right_unique")

#Merging left data
disagree_db_wide <- merge(disagree_db, sensitivity_scores_left, by = "SubjectID_left_unique", all.x = TRUE, all.y = TRUE )

#Merging right data
disagree_db_wide <- merge(disagree_db_wide, sensitivity_scores_right, by = "SubjectID_right_unique", all.x = TRUE, all.y = TRUE )


```

#Excluding KK from the data 
```{r}
disagree_db_wide <- filter(disagree_db_wide, group_id != "25_KK_27" & group_id != "25_KK_28")
```


#Skill difference

```{r calculating skill difference}
disagree_db_wide$skill_dif <- 0 #Creating column of 0
disagree_db_wide$skill_dif <- ifelse(disagree_db_wide$chosen_leader == "Left_lead", disagree_db_wide$Slope_left/disagree_db_wide$Slope_right, disagree_db_wide$Slope_right/disagree_db_wide$Slope_left) #calculating skill difference as a ratio between leader and follower sensitivity
disagree_db_wide$skill_dif_c <- (disagree_db_wide$skill_dif)-1

```

#Confidence difference

```{r calculating confidence difference }
#Making the responses absolute numbers
disagree_db_wide$Response_left_abs<- abs(disagree_db_wide$Response_left)
disagree_db_wide$Response_right_abs<- abs(disagree_db_wide$Response_right)

#Left response scaled
disagree_db_wide <- scale_within(disagree_db_wide, variables = "Response_left_abs", within = "SubjectID_left_unique", center = TRUE, scale = TRUE, prefix = "z_")

#Right response scaled
disagree_db_wide <- scale_within(disagree_db_wide, variables = "Response_right_abs", within = "SubjectID_right_unique", center = TRUE, scale = TRUE, prefix = "z_")

#Creating ratio
disagree_db_wide$conf_dif <- 0 #Creating column of 0
disagree_db_wide$conf_dif <- ifelse(disagree_db_wide$chosen_leader == "Left_lead", disagree_db_wide$Response_left_abs/disagree_db_wide$Response_right_abs, disagree_db_wide$Response_right_abs/disagree_db_wide$Response_left_abs) #calculating confidence difference as a ratio between leader and follower confidence
disagree_db_wide$conf_dif_c <- (disagree_db_wide$conf_dif)-1

```



#Back to long format (to use in model)

```{r make long format}

#create dataframe with only data from left player
disagree_left <- disagree_db_wide %>% select(-contains('right'))

#make sure there is only the relevent information ofr the participant
disagree_left$skill_dif[disagree_left$chosen_leader != 'Left_lead'] <- NA #insert NAs for chosen leader if not left

disagree_left$conf_dif[disagree_left$chosen_leader != 'Left_lead'] <- NA #insert NAs for chosen leader if not left

disagree_left$skill_dif_c[disagree_left$chosen_leader != 'Left_lead'] <- NA #insert NAs for chosen leader if not left

disagree_left$conf_dif_c[disagree_left$chosen_leader != 'Left_lead'] <- NA #insert NAs for chosen leader if not left

disagree_left$leader_behavior[disagree_left$chosen_leader != 'Left_lead'] <- NA #insert NAs for chosen leader if not left
disagree_left$Leader_gender[disagree_left$chosen_leader != 'Left_lead'] <- NA #insert NAs for chosen leader if not left

disagree_left$Follower_gender[disagree_left$chosen_leader != 'Left_lead'] <- NA #insert NAs for chosen leader if not left

#create dataframe with only data from right player
disagree_right <- disagree_db_wide %>% select(-contains('left'))

#make sure there is only the relevent information ofr the participant
disagree_right$skill_dif[disagree_right$chosen_leader != 'Right_lead'] <- NA #insert NAs for chosen leader if not left

disagree_right$conf_dif[disagree_right$chosen_leader != 'Right_lead'] <- NA #insert NAs for chosen leader if not left

disagree_right$skill_dif_c[disagree_right$chosen_leader != 'Right_lead'] <- NA #insert NAs for chosen leader if not left

disagree_right$conf_dif_c[disagree_right$chosen_leader != 'Right_lead'] <- NA #insert NAs for chosen leader if not left

disagree_right$leader_behavior[disagree_right$chosen_leader != 'Right_lead'] <- NA #insert NAs for chosen leader if not left
disagree_right$Leader_gender[disagree_right$chosen_leader != 'Right_lead'] <- NA #insert NAs for chosen leader if not left

disagree_right$Follower_gender[disagree_right$chosen_leader != 'Right_lead'] <- NA #insert NAs for chosen leader if not left


#rename columns to not contain left or right
names(disagree_left) <- gsub(pattern = "_left", replacement = "", x = names(disagree_left))

names(disagree_right) <- gsub(pattern = "_right", replacement = "", x = names(disagree_right))


#make same type of column in subject
disagree_right$SubjectID <- as.factor(disagree_right$SubjectID)
disagree_left$SubjectID <- as.factor(disagree_left$SubjectID)

#make column that specifies side
disagree_right$Side <- as.factor("right")
disagree_left$Side <- as.factor("left")


#Joining the dataframes
disagree_db_long <- rbind(disagree_left, disagree_right)

#remove nas from data, so only containing leader information 
disagree_db_long <- na.omit(disagree_db_long)

```


#Dummy coding the leader behaviour variabel
```{r dummy coding the leader bevhaiour}
disagree_db_long$leader_behavior <- ifelse(disagree_db_long$leader_behavior == "surrender", 1, 0)
```


#Write CSV
```{r creating CSV}

write.csv(disagree_db_wide, file = "disagree_sensitivity_db_wide.csv")
write.csv(disagree_db_long, file = "disagree_sensitivity_db_long.csv")

```



