---
title: "Gender_bias"
author: "Thea Rolskov Sloth"
date: "12/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Getting packages
```{r loading packages, include = FALSE}
library(pacman)
p_load(brms, tidyverse, tidybayes, ggplot2, LaplacesDemon, rethinking, tidyr, reshape2, tibble, plotly, jpeg, tm, ggrepel, utils, igraph)
```

#Setting directory
```{r}
setwd("~/Bachelor-MM-/") #TRS
```

#Loading data
```{r}
data_ib <- read.csv("implicit_bias/data_ib.csv")[,2:12]
data_eb <- read.csv("explicit_bias/eb_results.csv")[, 2:6]
data_db <- read.csv("decision_bias/disagree_sensitivity_db_long.csv")[, 2:44]
data_db_all <- read.csv("decision_bias/data_db_all.csv")
```

#Creating new data frame with relevant variables for gender bias
```{r}
#Selecting age, gender, ID
data_gb <- unique(data_ib[, 1:3])

#Adding rt dif
data_gb$rt_dif <- as.data.frame(ranef(model_ib2))[, 5]

#Adding sexism scores
data_gb <- merge(data_gb, data_eb[,1:3])

#adding random effect of decision bias 
data_gb$DB <- as.data.frame(ranef(model_db2_ID))[, 5]
data_gb$DB_conf <- as.data.frame(ranef(model_db2_ID))[, 9] - as.data.frame(ranef(model_db2_ID))[, 13]
data_gb$DB_skill <- as.data.frame(ranef(model_db2_ID))[, 17] - as.data.frame(ranef(model_db2_ID))[, 21]


#Save estimates in cv for Riccardo
write.csv(data_gb, file = "data_gender_bias.csv" )
```


```{r divide data in gender}
data_gb_male <- filter(data_gb, gender == "Male")
data_gb_female <- filter(data_gb, gender == "Female")

```



#Network analysis
```{r grand finale}
#prior for gb model

prior_gb <- c(
 prior(normal(0,1), class=Intercept),
 prior(lkj(5), class=rescor)
)

#female netowrk
gb_model1_f <- brm(
  mvbind(benevolent_score, hostile_score, rt_dif, DB, DB_skill, DB_conf) ~ 1,
  data = data_gb_female, 
  chains = 2,
  iter = 8000,
  cores = 2,
  sample_prior=T,
  prior = prior_gb, 
  family = gaussian, 
  control = list(adapt_delta = 0.99, max_treedepth = 15))


#male network model
gb_model1_m <- brm(
  mvbind(benevolent_score, hostile_score, rt_dif, DB, DB_skill, DB_conf) ~ 1,
  data = data_gb_male, 
  chains = 2,
  iter = 8000,
  cores = 2,
  sample_prior=T,
  prior = prior_gb, 
  family = gaussian, 
  control = list(adapt_delta = 0.99, max_treedepth = 15))


cor_f <- as.data.frame(vcov(gb_model1_f, correlation = TRUE))
cor_m <- as.data.frame(vcov(gb_model1_m, correlation = TRUE))


gb_model1_f_try <- brm(
  mvbind(benevolent_score, hostile_score, rt_dif, DB, DB_skill, DB_conf) ~ 1  + (1|ID),
  data = data_gb_female, 
  chains = 2,
  iter = 8000,
  cores = 2,
  sample_prior=T,
  prior = prior_gb, 
  family = gaussian, 
  control = list(adapt_delta = 0.99, max_treedepth = 15))

cor_f_try <- as.data.frame(vcov(gb_model1_f_try, correlation = TRUE))
write.csv(cor_f_try, file = "cor_f_try.csv")
```


```{r prepare dataframe}
#put Na in diagonal
diag(cor_f) = NA

diag(cor_m) = NA

#change column names
names(cor_f) <- c("Benevolent", "Hostile", "Implicit bias", "Decision bias", "Skill", "Confidence")
names(cor_m) <- c("Benevolent", "Hostile", "Implicit bias", "Decision bias", "Skill", "Confidence")

row.names(cor_f) <- c("Benevolent", "Hostile", "Implicit bias", "Decision bias", "Skill", "Confidence")
row.names(cor_m) <- c("Benevolent", "Hostile", "Implicit bias", "Decision bias", "Skill", "Confidence")


write.csv(cor_f, file = "cor_f.csv")
write.csv(cor_m, file = "cor_m.csv")


#plot network

V(cor_f)

cor_f[]

plot(cor_f, edge.arrow.size=.5)

eg <- make_empty_graph(40)
plot(eg, vertex.size=10, vertex.label=NA)



```


  mvbind(benevolent_score, hostile_score, rt_dif, DB, DB_skill, DB_conf) ~ 1  + (1|p|ID), 

#Make network plot
```{r}
cor_f <- read.csv("cor_f.csv")[1:4,1:5]
cor_f <- column_to_rownames(cor_f, loc = 1)

cor_m <- read.csv("cor_m.csv")[1:4,1:5]
cor_m <- column_to_rownames(cor_m, loc = 1)



```

#MEN
```{r}
#Reshaping the data frame
cor_m_df <- data.frame(FROM=rownames(cor_m)[row(cor_m)], TO=colnames(cor_m)[col(cor_m)], corr=do.call(c, c(cor_m)))

cor_m_df$TO <- gsub("\\.", " ", cor_m_df$TO)

###Edges

#Adding variables of negative and positive correlation
cor_m_df$corr_dir <- ifelse(cor_m_df$corr < 0, 1, 2)

#Tranformsing the correlations into absolute values
cor_m_df$corr <- abs(cor_m_df$corr)

#Removing edges below 0.1
cor_m_df$corr[cor_m_df$corr<0.01] <- NA

###Nodes
nodes <- as.data.frame(as.character(unique(cor_m_df[,1])))


###PLOTTING

#Creating graph object
net_m <- graph_from_data_frame(d=cor_m_df, vertices=nodes, directed=F) 

#Removing loops 
net_m <- simplify(net_m, remove.multiple = F, remove.loops = T) 


#Adding edge color based on positive or negative correlation
colrs <- c("orange", "blue")

E(net_m)$color <- colrs[E(net_m)$corr_dir]

# Set edge width based on weight:
E(net_m)$width <- E(net_m)$corr*15

E(net_m)$length <- 1/(E(net_m)$corr)*15

plot(net_m, vertex.label.color="black", vertex.label.dist=3, vertex.size=14, vertex.color="black", edge.curved=0, main = "Correlation plot (males)", layout = layout_nicely)

legend(x=-1.3, y=-1.1, c("Negative correlation","Positive correlation"), pch=21,

       col="#777777", pt.bg=colrs, pt.cex=2, cex=.8, bty="n", ncol=1)


```

#WOMEN
```{r}
#Reshaping the data frame
cor_f_df <- data.frame(FROM=rownames(cor_f)[row(cor_f)], TO=colnames(cor_f)[col(cor_f)], corr=do.call(c, c(cor_f)))

cor_f_df$TO <- gsub("\\.", " ", cor_f_df$TO)

###Edges

#Adding variables of negative and positive correlation
cor_f_df$corr_dir <- ifelse(cor_f_df$corr < 0, 1, 2)

#Tranformsing the correlations into absolute values
cor_f_df$corr <- abs(cor_f_df$corr)

#Removing edges below 0.1
cor_f_df$corr[cor_f_df$corr<0.01] <- NA

###Nodes
nodes <- as.data.frame(as.character(unique(cor_f_df[,1])))


###PLOTTING

#Creating graph object
net_f <- graph_from_data_frame(d=cor_f_df, vertices=nodes, directed=F) 

#Removing loops 
net_f <- simplify(net_f, remove.multiple = F, remove.loops = T) 


#Adding edge color based on positive or negative correlation
colrs <- c("orange", "blue")

E(net_f)$color <- colrs[E(net_f)$corr_dir]

# Set edge width based on weight:
E(net_f)$width <- E(net_f)$corr*15

E(net_f)$length <- 1/(E(net_f)$corr)*15

plot(net_f, vertex.label.color="black", vertex.label.dist=3, vertex.size=14, vertex.color="black", edge.curved=0, main = "Correlation plot (females)", layout = layout_nicely)

legend(x=-1.3, y=-1.1, c("Negative correlation","Positive correlation"), pch=21,

       col="#777777", pt.bg=colrs, pt.cex=2, cex=.8, bty="n", ncol=1)


```





#skal slettes efter

#Make network plot
```{r}
cor_f_try <- read.csv("cor_f_try.csv")[1:4,1:5]
cor_f_try <- column_to_rownames(cor_f_try, loc = 1)


```



#WOMEN
```{r}
#Reshaping the data frame
cor_f_try_df <- data.frame(FROM=rownames(cor_f_try)[row(cor_f_try)], TO=colnames(cor_f_try)[col(cor_f_try)], corr=do.call(c, c(cor_f_try)))

cor_f_try_df$TO <- gsub("\\.", " ", cor_f_try_df$TO)

###Edges

#Adding variables of negative and positive correlation
cor_f_try_df$corr_dir <- ifelse(cor_f_try_df$corr < 0, 1, 2)

#Tranformsing the correlations into absolute values
cor_f_try_df$corr <- abs(cor_f_try_df$corr)

#Removing edges below 0.1
cor_f_try_df$corr[cor_f_try_df$corr<0.01] <- NA

###Nodes
nodes <- as.data.frame(as.character(unique(cor_f_try_df[,1])))


###PLOTTING

#Creating graph object
net_f <- graph_from_data_frame(d=cor_f_try_df, vertices=nodes, directed=F) 

#Removing loops 
net_f <- simplify(net_f, remove.multiple = F, remove.loops = T) 


#Adding edge color based on positive or negative correlation
colrs <- c("orange", "blue")

E(net_f)$color <- colrs[E(net_f)$corr_dir]

# Set edge width based on weight:
E(net_f)$width <- E(net_f)$corr*15

E(net_f)$length <- 1/(E(net_f)$corr)*15

plot(net_f, vertex.label.color="black", vertex.label.dist=3, vertex.size=14, vertex.color="black", edge.curved=0, main = "Correlation plot (females)", layout = layout_nicely)

legend(x=-1.3, y=-1.1, c("Negative correlation","Positive correlation"), pch=21,

       col="#777777", pt.bg=colrs, pt.cex=2, cex=.8, bty="n", ncol=1)


```




