
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(pacman)
library(plyr)
library(dplyr)
library(DataCombine)
library(lme4)

setwd("~/Bachelor-MM-/implicit_bias")


```

LOAD DATA
```{r}
d = list.files(path = "/implicit_data/⁩",full.names T , pattern = "logfile") #create list including all csv file 

data1 <- ldply(temp1, read.csv)

data1$X = NULL

```

PHILOSOPHY - HISTORY - HISTORY OF IDEAS
```{r}
temp2 = list.files(path = "C:/Users/kathr/OneDrive/COGNITIVE SCIENCE/4. semester/Social and cultural dynamics in cognition/Exam/Experiment data/Philosophy - History of Ideas - History",full.names = T,pattern="*.csv")

data2 <- ldply(temp2, read.csv)

data2$X = NULL
data2$?.. = NULL

```

COGNITIVE SCIENCE
```{r}
temp3 = list.files(path = "C:/Users/kathr/OneDrive/COGNITIVE SCIENCE/4. semester/Social and cultural dynamics in cognition/Exam/Experiment data/Cognitive Science",full.names = T,pattern="*.csv")

data3 <- ldply(temp3, read.csv)

data3$X = NULL
data3$?.. = NULL

```

MERGNING THE DATA FROM DIFFERENT EDUCATIONS TOGETHER 
```{r}
all_data = merge(data1, data2, all = TRUE)

all_data = merge(all_data, data3, all = TRUE)

```

SUBSETTING THE DATA BASED ON THE INTERESTING BLOCKS 
```{r}

data <- subset(all_data, block == 3 | block == 4 | block == 6 | block == 7)

#data = subset(data, select = -(?..))

#data$X <- NULL

```


LOG TRANFORMING THE RT DATA
```{r}

data$rtlog <- log(data$rt)

```


MAKING A COLUMN TO USE FOR PLOTS ABOUT EDUCATION AREAS 
```{r}

data$edu_area <- NA

data[data$education == "Cognitive Science",]$edu_area <- "Arts-Science"

data[data$education == "Biology",]$edu_area <- "Science-Science"

#data[data$education == "Molecular Biology",]$edu_area <- "Science-Science"

data[data$education == "Philosophy",]$edu_area <- "Arts-Arts"

#data[data$education == "History",]$edu_area <- "Arts-Arts"

#data[data$education == "History of Ideas",]$edu_area <- "Arts-Arts"

```

ADDING THE CONGRUENT VARIABLE
```{r}
#make a column with contrasts to use as main effect in orer to investigate the correct blocks and their rt 
#block 1, 2, 5 --> 0 
#block 3, 4 --> -0.5 (combined are they 1)
#block 6, 7 --> +0.5 (combined are they 1 )

data$condition <- 0 
data[data$block == 3,]$condition <- 0
data[data$block == 4,]$condition <- 0
data[data$block == 6,]$condition <- 1
data[data$block == 7,]$condition <- 1

```


```{r}
#calculate difference in average speed per participant using  B4 & B7 and B3 & B6 

meanrt <- data.frame(matrix(ncol=3))

n=1
#average rt per participant per block 
for (i in unique(data$ID)){
  for (x in unique(data$block)){
    tempdata <- subset(data, ID==i & block==x)
    meanrt[n,1] <- i
    meanrt[n,2] <- x
    meanrt[n,3] <- mean(tempdata$rt)
    n=n+1
  }
}

colnames(meanrt) <- c("ID", "block", "mean_rt")

```


PLOT ON PARTICIPANT EDUCATION 
```{r}

ggplot(data = data, (aes(x = semester, fill = edu_area))) +  
  scale_fill_brewer(palette="Set1") +
  geom_bar() +
  labs(title = "Participants: semester overview") + 
  facet_wrap(~ gender)



#colorfun
#http://www.sthda.com/english/wiki/ggplot2-colors-how-to-change-colors-automatically-and-manually#change-colors-manually

```



```{r}
#ggplot(meanrt, aes(x = gender, y = rt)) +
#  geom_col() +
#  facet_wrap(~edu_area)


#ggplot(meanrt, aes(x = block, y = rt, color = ID)) + 
# geom_point()

#plot error bars! 



```


```{r}
#the following is based on table 3.3 from google docs 

#step to scoring the IAT data 

#1: delete trials greater than 10.000 milliseconds
#my approach: investigate if rt > 10.000 

#adding a test row 
#testrow <- c("TESTER",22, "Female", "Arts","e", "e", 11.4867483, 3, "Biology", 2, 4, NA)
#data <- InsertRow(data, testrow)

data$rt_less_than_10s <- NA

data$rt <- as.numeric(data$rt)

#data[data$rt > 10,]$rt_less_than_10s <- "NO"
data[data$rt < 10,]$rt_less_than_10s <- "YES"

#checking the answers from the columns above - if only YES is displayed, it is all good
count(data$rt_less_than_10s)



#2:delete subjects who has  10 % trials with a rt less than 300 milliseconds (0.3 seconds)
#they have not been doing the task properly, perhaps some theory about this speed of thinking? 
#my approach: first look for rt < 300 and hope there are not that many, perhaps I can calculate it by looking a the number of totalt trials per person and then find out how many trials 10 % is 

data$rt_more_than_0.3s <- NA 

data$rt <- as.numeric(data$rt)

data[data$rt > 0.3,]$rt_more_than_0.3s <- "YES" 
data[data$rt < 0.3,]$rt_more_than_0.3s <- "NO"

#checking the answers from the columns above - if only YES is displayed, it is all good
count(data$rt_more_than_0.3s) 

#if some of the participants has trials which they have rt less than 300 milliseonds, then remember the 10 % investigation 

#Removing NO rows 
data <- data[!(data$rt_more_than_0.3s == "NO"),]   


```


WRITING A CSV FILE WITH THE DATA
```{r}

data$rt_less_than_10s <- NULL
data$rt_more_than_0.3s <- NULL

write.csv(data, file = "iat_data.csv")

```


```{r}
##filtering the critical blocks B3, B4 and B6, B7

# block3 <- all_data %>%
#   subset(block == 3)
# 
# block4 <- all_data %>%
#   subset(block == 4)
# 
# block6 <- all_data %>%
#   subset(block == 6)
# 
# block7 <- all_data %>%
#   subset(block == 7)
# 
# block3_4 = merge(block3, block4, all=TRUE) 
# block6_7 = merge(block6, block7, all=TRUE)
# 
# data = merge(block3_4, block6_7, all=TRUE)                        
# 
# data$ID <- as.character(data$ID)
# data$rt <- as.numeric(data$rt)
# 
# 
# #deleting not necessary dføs in the environmemt 
# 
# #block3 <- NULL
# #block4 <- NULL
# #block6 <- NULL
# #block7 <- NULL
# #block3_4 <- NULL
# #block6_7 <- NULL
# 
# block3_6 <- merge(block3, block6, all = TRUE)
# block4_7 <- merge(block4, block7, all = TRUE)

```

