---
title: "Preprocessing, Implicit"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Getting packages
```{r loading packages, include = FALSE}

library(pacman)

p_load(brms, tidyverse, tidybayes, ggplot2, LaplacesDemon, rethinking, tidyr, reshape2, tibble, plotly, jpeg, tm)
```

#Loading data
```{r loading data}
path_ib = "~/Cognitive Science/5. Semester/Bachelor, MM/GIT/Bachelor-MM-/implicit_bias/implicit_data/"

#Listing files in path
files <- list.files(path = path_ib)

#Create empty data frame
ib_data <- data.frame(matrix(ncol = 10, nrow = 0))

#Looping through data files and inserting in dataframe
for (i in files) {
  d <- read.delim(file = paste(path_ib, i, sep = ""), sep = ",", header = TRUE)
  ib_data = rbind(ib_data,d)
}

#removing first column
ib_data <- ib_data[, 2:10]

```

#Subsetting data from incongruent conditions with two groups
```{r}
ib_data <- subset(ib_data, block == 3 | block == 4 | block == 6 | block == 7)
```


#Adding a column with condition: 1 = Incongruent, 0 = Congruent
```{r}
ib_data$condition <- 0 

ib_data[ib_data$block == 3,]$condition <- 0
ib_data[ib_data$block == 4,]$condition <- 0
ib_data[ib_data$block == 6,]$condition <- 1
ib_data[ib_data$block == 7,]$condition <- 1

```


#Log-transforming RT-data
```{r}
ib_data$rt_log <- log(ib_data$rt)
```

#calculate difference in average speed per participant using  B4 & B7 and B3 & B6

```{r}

#Benevolent sexism score questions
benevolent_questions = c(1, 3, 6, 8, 9, 12, 13, 17, 19, 20, 22)

#Averaging questions relating to hostile sexism score per participant
ib_results <- ib_data %>% group_by(ID) %>% summarise(mean_RT = mean(rt))




meanrt <- data.frame(matrix(ncol=3))





n=1

1#average rt per participant per block 
for (i in unique(ib_data$ID)){
  for (x in unique(data$block)){
    tempdata <- subset(data, ID==i & block==x)
    meanrt[n,1] <- i
    meanrt[n,2] <- x
    meanrt[n,3] <- mean(tempdata$rt)
    n=n+1
  }
}

colnames(meanrt) <- c("ID", "block", "mean_rt")

```


